# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Files/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .responsive import capture_widget_geometries, scale_widget_geometries
from .scrap_window import ScrapingWindow
from .sort_window import SortingWindow
from .search_window import SearchingWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 50, 290, 35))
        
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(65)
        
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        
        self.scrapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.scrapBtn.setGeometry(QtCore.QRect(280, 210, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrapBtn.setFont(font)
        self.scrapBtn.setObjectName("scrapBtn")
        self.scrapBtn.clicked.connect(lambda: self.go_to_scrap_window(MainWindow))
        
        self.sortBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sortBtn.setGeometry(QtCore.QRect(280, 290, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sortBtn.setFont(font)
        self.sortBtn.setObjectName("sortBtn")
        self.sortBtn.clicked.connect(lambda: self.go_to_sort_window(MainWindow))
        
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(280, 370, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.searchBtn.clicked.connect(lambda: self.go_to_search_window(MainWindow))
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project"))
        self.label.setText(_translate("MainWindow", "DSA Scraping Project"))
        self.scrapBtn.setText(_translate("MainWindow", "Scrap EBooks"))
        self.sortBtn.setText(_translate("MainWindow", "Sort Data"))
        self.searchBtn.setText(_translate("MainWindow", "Search Data"))
        
    def go_to_scrap_window(self, MainWindow):
        self.scraping_window = ScrapingWindow(MainWindow)
        self.scraping_window.show()
        QtWidgets.QApplication.instance().activeWindow().hide()

    def go_to_sort_window(self, MainWindow):
        self.sorting_window = SortingWindow(MainWindow)
        self.sorting_window.show()
        QtWidgets.QApplication.instance().activeWindow().hide()
        
        
    def go_to_search_window(self, MainWindow):
        self.searching_window = SearchingWindow(MainWindow)
        self.searching_window.show()
        QtWidgets.QApplication.instance().activeWindow().hide()


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self._base_size = QtCore.QSize(800, 600)
        self._widget_geometries = capture_widget_geometries(self.ui.centralwidget)

    def resizeEvent(self, event):
        current_size = self.ui.centralwidget.size()
        if current_size.width() < 100 or current_size.height() < 100:
            super().resizeEvent(event)
            return
        scale_widget_geometries(self._widget_geometries, self._base_size, self.ui.centralwidget.size())
        super().resizeEvent(event)


def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
