# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Files/ScrapingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import time
import re
from selenium import webdriver
from bs4 import BeautifulSoup
from selenium.webdriver.chrome.service import Service
from PyQt5.QtCore import QThread, pyqtSignal
from pathlib import Path
import os
from .config import get_chromedriver_path, save_chromedriver_path, CHROMEDRIVER_CONFIG_FILE
from .responsive import capture_widget_geometries, scale_widget_geometries


class ScraperThread(QThread):
    update_progress = pyqtSignal(int)
    update_table = pyqtSignal(pd.DataFrame)
    scraping_finished = pyqtSignal()

    def __init__(self, number_of_books, chromedriver_path):
        super().__init__()
        self.number_of_books = number_of_books
        self.chromedriver_path = chromedriver_path
        self.pause_flag = False
        self.stop_flag = False

    def run(self):
        total_pages = self.number_of_books // 50
        if total_pages <= 0:
            total_pages = 1

        service = Service(executable_path=self.chromedriver_path)
        options = webdriver.ChromeOptions()
        driver = webdriver.Chrome(service=service, options=options)

        ISBNs, titles, subtitles, authors, book_links, publish_years, prices = [], [], [], [], [], [], []

        base_url = "https://single-ebooks.springernature.com/search?query=science&pageNumber={}&size=50"
        for page in range(1, total_pages + 1):
            if self.stop_flag:
                break  

            while self.pause_flag:
                time.sleep(0.5) 

            url = base_url.format(page)
            driver.get(url)
            time.sleep(1)  
            content = driver.page_source
            soup = BeautifulSoup(content, "html.parser")

            books = soup.find_all("li", attrs={"id": "eBookResultItem"})
            
            for book in books:
                isbn = book.find("div", class_="ebook-eisbn")
                isbn_text = isbn.find("b")
                ISBNs.append(isbn_text.text.strip() if isbn_text else "Unavailable")

                title = book.find("div", class_="ebook-title")
                title_name = title.find("a", href=True)
                titles.append(title_name.text.strip() if title_name else "Unavailable")

                book_links.append(title_name["href"] if title_name else "Unavailable")
                
                subtitle = book.find("div", class_="ebook-subtitle")
                subtitles.append(subtitle.text.strip() if subtitle and subtitle.text != '' else "Unavailable")

                author = book.find("div", class_="ebook-author")
                authors.append(author.text.strip() if author else "Unavailable")

                publish_year = book.find("div", class_="ebook-year")
                publish_years.append(publish_year.text.strip().replace(",", "").split(' ')[0].strip() if publish_year else "Unavailable")

                price = book.find("p", class_="price")
                if price:
                    price_digits_only = re.sub(r'\D', '', price.text.strip())
                    prices.append(int(price_digits_only) if price_digits_only else 0)
                else:
                    prices.append(0)

            progress = int((page / total_pages) * 100)
            self.update_progress.emit(progress)
            QtCore.QCoreApplication.processEvents()

        ebook_data = {
            "ISBN": ISBNs,
            "Title": titles,
            "Subtitle": subtitles,
            "Authors": authors,
            "Publish Year": publish_years,
            "eBook Link": book_links,
            "Price": prices
        }
        ebook_df = pd.DataFrame(ebook_data)

        self.update_table.emit(ebook_df)
        driver.quit()
        self.scraping_finished.emit()

    def pause(self):
        self.pause_flag = True

    def resume(self):
        self.pause_flag = False

    def stop(self):
        self.stop_flag = True
        self.pause_flag = False


class Ui_ScrapingWindow(object):
    def setupUi(self, ScrapingWindow):
        ScrapingWindow.setObjectName("ScrapingWindow")
        ScrapingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ScrapingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(130, 5, 540, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(60)
        
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        
        self.numberLB = QtWidgets.QLabel(self.centralwidget)
        self.numberLB.setGeometry(QtCore.QRect(150, 50, 230, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.numberLB.setFont(font)
        self.numberLB.setObjectName("numberLB")
        
        self.numberCB = QtWidgets.QComboBox(self.centralwidget)
        self.numberCB.setGeometry(QtCore.QRect(450, 50, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.numberCB.setFont(font)
        self.numberCB.setObjectName("numberCB")
        
        self.numberCB.addItem("  500")
        for i in range(1, 11):
            self.numberCB.addItem(f"  {i * 1000}")
        self.numberCB.addItem("  15000")
        self.numberCB.addItem("  20000")
        self.numberCB.addItem("  25000")
        
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(200, 100, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.startBtn.setFont(font)
        self.startBtn.setFlat(False)
        self.startBtn.setObjectName("startBtn")
        self.startBtn.clicked.connect(self.start_scraping)
        
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setGeometry(QtCore.QRect(200, 140, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stopBtn.setFont(font)
        self.stopBtn.setFlat(False)
        self.stopBtn.setObjectName("stopBtn")
        self.stopBtn.clicked.connect(self.stop_scraping)
        
        self.resumeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resumeBtn.setEnabled(False)
        self.resumeBtn.setGeometry(QtCore.QRect(450, 100, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.resumeBtn.setFont(font)
        self.resumeBtn.setFlat(False)
        self.resumeBtn.setObjectName("resumeBtn")
        self.resumeBtn.clicked.connect(self.resume_scraping)
        
        self.pauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pauseBtn.setEnabled(False)
        self.pauseBtn.setGeometry(QtCore.QRect(450, 140, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pauseBtn.setFont(font)
        self.pauseBtn.setFlat(False)
        self.pauseBtn.setObjectName("pauseBtn")
        self.pauseBtn.clicked.connect(self.pause_scraping)
        
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 180, 700, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 220, 780, 370))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        
        self.gobackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.gobackBtn.setGeometry(QtCore.QRect(0, 0, 70, 25))
        self.gobackBtn.setObjectName("gobackBtn")
        
        ScrapingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ScrapingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        ScrapingWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(ScrapingWindow)
        self.statusbar.setObjectName("statusbar")
        ScrapingWindow.setStatusBar(self.statusbar)
        
        self.actionSet_ChromeDriver = QtWidgets.QAction(ScrapingWindow)
        self.actionSet_ChromeDriver.setObjectName("actionSet_ChromeDriver")
        self.actionSet_ChromeDriver.triggered.connect(self.set_chromedriver_path)
        
        self.actionSave_CSV = QtWidgets.QAction(ScrapingWindow)
        self.actionSave_CSV.setEnabled(False)
        self.actionSave_CSV.setObjectName("actionSave_CSV")
        self.actionSave_CSV.triggered.connect(self.save_csv)
        
        self.menuOptions.addAction(self.actionSet_ChromeDriver)
        self.menuOptions.addAction(self.actionSave_CSV)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(ScrapingWindow)
        QtCore.QMetaObject.connectSlotsByName(ScrapingWindow)
        
        self.scraper_thread = None
        self.scraped_data = None
        self.ebook_data = None

    def retranslateUi(self, ScrapingWindow):
        _translate = QtCore.QCoreApplication.translate
        ScrapingWindow.setWindowTitle(_translate("ScrapingWindow", "Scraping Window"))
        self.title.setText(_translate("ScrapingWindow", "Scrap EBooks from www.single-ebooks.springernature.com"))
        self.numberLB.setText(_translate("ScrapingWindow", "Select No. of eBooks to Scrap"))
        self.startBtn.setText(_translate("ScrapingWindow", "Start"))
        self.stopBtn.setText(_translate("ScrapingWindow", "Stop"))
        self.resumeBtn.setText(_translate("ScrapingWindow", "Resume"))
        self.pauseBtn.setText(_translate("ScrapingWindow", "Pause"))
        self.gobackBtn.setText(_translate("ScrapingWindow", "<-  Back"))
        
        self.menuOptions.setTitle(_translate("ScrapingWindow", "Options"))
        self.actionSet_ChromeDriver.setText(_translate("ScrapingWindow", "Set ChromeDriver Path"))
        self.actionSave_CSV.setText(_translate("ScrapingWindow", "Save CSV"))
        self.actionSave_CSV.setShortcut(_translate("ScrapingWindow", "Ctrl+S"))
         
    def start_scraping(self):
        number_of_books = int(self.numberCB.currentText().strip())
        chromedriver_path = get_chromedriver_path()

        if not chromedriver_path or not Path(chromedriver_path).exists():
            QtWidgets.QMessageBox.warning(
                None,
                "ChromeDriver Not Set",
                "Set a valid ChromeDriver path from Options before starting scraping."
            )
            return

        self.scraper_thread = ScraperThread(number_of_books, chromedriver_path)
        self.scraper_thread.update_progress.connect(self.update_progress_bar)
        self.scraper_thread.update_table.connect(self.populate_table)
        self.scraper_thread.scraping_finished.connect(self.scraping_finished)

        self.scraper_thread.start()
        self.startBtn.setEnabled(False)
        self.pauseBtn.setEnabled(True)
        self.stopBtn.setEnabled(True)
        self.resumeBtn.setEnabled(False)
        self.actionSave_CSV.setEnabled(False)

    def stop_scraping(self):
        if self.scraper_thread:
            self.scraper_thread.stop()
        self.pauseBtn.setEnabled(False)
        self.resumeBtn.setEnabled(False)
        self.stopBtn.setEnabled(False)
        self.startBtn.setEnabled(True)
        self.actionSave_CSV.setEnabled(True)

    def pause_scraping(self):
        if self.scraper_thread:
            self.scraper_thread.pause()
        self.pauseBtn.setEnabled(False)
        self.resumeBtn.setEnabled(True)
        self.stopBtn.setEnabled(True)
        self.startBtn.setEnabled(False)

    def resume_scraping(self):
        if self.scraper_thread:
            self.scraper_thread.resume()
        self.pauseBtn.setEnabled(True)
        self.stopBtn.setEnabled(True)
        self.resumeBtn.setEnabled(False)
        self.startBtn.setEnabled(False)

    def update_progress_bar(self, progress):
        self.progressBar.setValue(progress)
             
    def populate_table(self, ebook_df):
        self.scraped_data = ebook_df 
        self.table.setColumnCount(len(ebook_df.columns))
        self.table.setRowCount(len(ebook_df))
        self.table.setHorizontalHeaderLabels(ebook_df.columns)
        for i in range(len(ebook_df)):
            for j in range(len(ebook_df.columns)):
                self.table.setItem(i, j, QtWidgets.QTableWidgetItem(str(ebook_df.iloc[i, j])))
        self.actionSave_CSV.setEnabled(True)
                   
    def scraping_finished(self):
        self.startBtn.setEnabled(True)
        self.pauseBtn.setEnabled(False)
        self.resumeBtn.setEnabled(False)
        self.stopBtn.setEnabled(False)
        self.progressBar.setValue(100)
              
    def save_csv(self):
        if self.scraped_data is not None:
            options = QtWidgets.QFileDialog.Options()
            options |= QtWidgets.QFileDialog.DontUseNativeDialog
            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save CSV", "", "CSV Files (*.csv);;All Files (*)", options=options)
            if file_path:
                self.scraped_data.to_csv(f"{file_path}.csv", index=False)
                QtWidgets.QMessageBox.information(None, "CSV Saved", f"Data saved successfully to {file_path}")
        else:
            QtWidgets.QMessageBox.warning(None, "No Data", "No data to save. Please scrape the data first.")

    def set_chromedriver_path(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            None,
            "Select ChromeDriver Executable",
            "",
            "Executable Files (chromedriver.exe);;All Files (*)",
            options=options,
        )

        if file_path:
            save_chromedriver_path(file_path)
            QtWidgets.QMessageBox.information(
                None,
                "ChromeDriver Path Saved",
                f"ChromeDriver path saved to {CHROMEDRIVER_CONFIG_FILE}"
            )


class ScrapingWindow(QtWidgets.QMainWindow):
    def __init__(self, main_window):
        super().__init__()
        self.ui = Ui_ScrapingWindow()
        self.ui.setupUi(self)
        self.main_window = main_window 
        self.ui.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self._base_size = QtCore.QSize(800, 600)
        self._widget_geometries = capture_widget_geometries(self.ui.centralwidget)

        self.ui.gobackBtn.clicked.connect(self.go_back_to_main)

    def resizeEvent(self, event):
        current_size = self.ui.centralwidget.size()
        if current_size.width() < 100 or current_size.height() < 100:
            super().resizeEvent(event)
            return
        scale_widget_geometries(self._widget_geometries, self._base_size, self.ui.centralwidget.size())
        super().resizeEvent(event)

    def go_back_to_main(self):
        self.main_window.show()
        self.close()
