# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Files/SearchWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from .responsive import capture_widget_geometries, scale_widget_geometries


class Ui_SearchingWindow(object):
    def setupUi(self, SearchingWindow):
        SearchingWindow.setObjectName("SearchingWindow")
        SearchingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SearchingWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gobackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.gobackBtn.setGeometry(QtCore.QRect(0, 0, 70, 25))
        self.gobackBtn.setObjectName("gobackBtn")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 5, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 45, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 80, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 120, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        self.column1CB = QtWidgets.QComboBox(self.centralwidget)
        self.column1CB.setGeometry(QtCore.QRect(300, 45, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.column1CB.setFont(font)
        self.column1CB.setObjectName("column1CB")
        
        self.column2CB = QtWidgets.QComboBox(self.centralwidget)
        self.column2CB.setGeometry(QtCore.QRect(300, 80, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.column2CB.setFont(font)
        self.column2CB.setObjectName("column2CB")
        
        self.filterCB = QtWidgets.QComboBox(self.centralwidget)
        self.filterCB.setGeometry(QtCore.QRect(300, 120, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filterCB.setFont(font)
        self.filterCB.setObjectName("filterCB")
        self.filterCB.addItem("")
        self.filterCB.addItem("")
        self.filterCB.addItem("")
        self.filterCB.addItem("")
        
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(600, 120, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.searchBtn.clicked.connect(self.search_data)
        
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(5, 170, 790, 400))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.searchTerm1 = QtWidgets.QLineEdit(self.centralwidget)
        self.searchTerm1.setGeometry(QtCore.QRect(575, 45, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.searchTerm1.setFont(font)
        self.searchTerm1.setObjectName("searchTerm1")
        self.searchTerm2 = QtWidgets.QLineEdit(self.centralwidget)
        self.searchTerm2.setGeometry(QtCore.QRect(575, 80, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.searchTerm2.setFont(font)
        self.searchTerm2.setObjectName("searchTerm2")
        SearchingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SearchingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        SearchingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SearchingWindow)
        self.statusbar.setObjectName("statusbar")
        SearchingWindow.setStatusBar(self.statusbar)
        self.actionOpen_CSV = QtWidgets.QAction(SearchingWindow)
        self.actionOpen_CSV.setObjectName("actionOpen_CSV")
        self.actionOpen_CSV.triggered.connect(self.load_csv)
        
        self.menuOptions.addAction(self.actionOpen_CSV)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(SearchingWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchingWindow)
        
        self.csv_data = None

    def retranslateUi(self, SearchingWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchingWindow.setWindowTitle(_translate("SearchingWindow", "Searching Window"))
        self.gobackBtn.setText(_translate("SortingWindow", "<- Back"))
        self.label.setText(_translate("SearchingWindow", "Search Through Data"))
        self.label_2.setText(_translate("SearchingWindow", "Select Column 1 :"))
        self.label_3.setText(_translate("SearchingWindow", "Select Column 2 :"))
        self.label_4.setText(_translate("SearchingWindow", "Select Filter :"))
        self.filterCB.setCurrentText(_translate("SearchingWindow", "None"))
        self.filterCB.setItemText(0, _translate("SearchingWindow", "None"))
        self.filterCB.setItemText(1, _translate("SearchingWindow", "AND"))
        self.filterCB.setItemText(2, _translate("SearchingWindow", "OR"))
        self.filterCB.setItemText(3, _translate("SearchingWindow", "NOT"))
        self.searchBtn.setText(_translate("SearchingWindow", "Search"))
        self.searchTerm1.setPlaceholderText(_translate("SearchingWindow", "Enter Search Term"))
        self.searchTerm2.setPlaceholderText(_translate("SearchingWindow", "Enter Second Term"))
        self.menuOptions.setTitle(_translate("SearchingWindow", "Options"))
        self.actionOpen_CSV.setText(_translate("SearchingWindow", "Open CSV"))
        self.actionOpen_CSV.setShortcut(_translate("SearchingWindow", "Ctrl+O"))
        
    def is_numeric_column(self, col_name):
        return pd.api.types.is_numeric_dtype(self.csv_data[col_name])
        
    def search_data(self):
        search_term1 = str(self.searchTerm1.text())
        search_term2 = str(self.searchTerm2.text())
        selected_col1 = self.column1CB.currentText()
        selected_col2 = self.column2CB.currentText()
        filter_text = self.filterCB.currentText()
        filtered_data = self.csv_data
        

        if not search_term1 or not selected_col1:
            return 
        
        # Apply first filter
        if self.is_numeric_column(selected_col1):
            try:
                search_value1 = float(search_term1)
                condition1 = self.csv_data[selected_col1] == search_value1
            except ValueError:
                return 
        else:
            condition1 = self.csv_data[selected_col1].str.contains(search_term1, case=False, na=False)
            
        if search_term2 and selected_col2:
            
            if self.is_numeric_column(selected_col2):
                try:
                    search_value2 = float(search_term2)
                    condition2 = self.csv_data[selected_col2] == search_value2
                except ValueError:
                    return 
            else:
                condition2 = self.csv_data[selected_col2].str.contains(search_term2, case=False, na=False)
                
            if filter_text == "AND":
                filtered_data = self.csv_data[condition1 & condition2]
            elif filter_text == "OR":
                filtered_data = self.csv_data[condition1 | condition2]
            elif filter_text == "NOT":
                filtered_data = self.csv_data[condition1 & ~condition2]
            else:
                filtered_data = self.csv_data[condition1]
        else:
            filtered_data = self.csv_data[condition1]

        self.populate_table(filtered_data)
        
    def load_csv(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open CSV", "", "CSV Files (*.csv);;All Files (*)", options=options)
        
        if file_path:
            try:
                self.csv_data = pd.read_csv(file_path)
                self.populate_table(self.csv_data)
                self.column1CB.addItems(self.csv_data.columns)
                self.column2CB.addItems(self.csv_data.columns)
            except Exception as e:
                QtWidgets.QMessageBox.critical(None, "Error", f"Could not load CSV file: {str(e)}")
                
                
    def populate_table(self, data_frame):
        self.table.setColumnCount(len(data_frame.columns))
        self.table.setRowCount(len(data_frame))
        self.table.setHorizontalHeaderLabels(data_frame.columns)
        
        for i in range(len(data_frame)):
            for j in range(len(data_frame.columns)):
                self.table.setItem(i, j, QtWidgets.QTableWidgetItem(str(data_frame.iloc[i, j])))


class SearchingWindow(QtWidgets.QMainWindow):
    def __init__(self, main_window):
        super().__init__()
        self.ui = Ui_SearchingWindow()
        self.ui.setupUi(self)
        self.main_window = main_window
        self.ui.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self._base_size = QtCore.QSize(800, 600)
        self._widget_geometries = capture_widget_geometries(self.ui.centralwidget)

        self.ui.gobackBtn.clicked.connect(self.go_back_to_main)

    def resizeEvent(self, event):
        current_size = self.ui.centralwidget.size()
        if current_size.width() < 100 or current_size.height() < 100:
            super().resizeEvent(event)
            return
        scale_widget_geometries(self._widget_geometries, self._base_size, self.ui.centralwidget.size())
        super().resizeEvent(event)

    def go_back_to_main(self):
        self.main_window.show()
        self.close()
