# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Files/SortingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal, QTimer
import pandas as pd
from time import time
from .algorithms import bubble_sort, insertion_sort, selection_sort, merge_sort, quick_sort, shell_sort, gnome_sort, counting_sort, radix_sort, bucket_sort
from .responsive import capture_widget_geometries, scale_widget_geometries


class Ui_SortingWindow(object):
    def setupUi(self, SortingWindow):
        SortingWindow.setObjectName("SortingWindow")
        SortingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SortingWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gobackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.gobackBtn.setGeometry(QtCore.QRect(0, 0, 70, 25))
        self.gobackBtn.setObjectName("gobackBtn")
        
        self.sortTitle = QtWidgets.QLabel(self.centralwidget)
        self.sortTitle.setGeometry(QtCore.QRect(350, 2, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(60)
        self.sortTitle.setFont(font)
        self.sortTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.sortTitle.setObjectName("sortTitle")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 65, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 100, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        
        self.columnSortCB = QtWidgets.QComboBox(self.centralwidget)
        self.columnSortCB.setGeometry(QtCore.QRect(300, 30, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.columnSortCB.setFont(font)
        self.columnSortCB.setObjectName("columnSortCB")
        
        self.algorithmCB = QtWidgets.QComboBox(self.centralwidget)
        self.algorithmCB.setGeometry(QtCore.QRect(300, 65, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.algorithmCB.setFont(font)
        self.algorithmCB.setObjectName("algorithmCB")
        self.algorithmCB.addItems([
            'Bubble Sort', 'Selection Sort', 'Insertion Sort', 
            'Merge Sort', 'Quick Sort', 'Counting Sort', 
            'Radix Sort', 'Bucket Sort', 'Shell Sort', 'Gnome Sort'
        ])
        
        self.timeLB = QtWidgets.QLabel(self.centralwidget)
        self.timeLB.setGeometry(QtCore.QRect(300, 100, 210, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.timeLB.setFont(font)
        self.timeLB.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLB.setObjectName("timeLB")
        
        self.sortTitle2 = QtWidgets.QLabel(self.centralwidget)
        self.sortTitle2.setGeometry(QtCore.QRect(300, 130, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(60)
        self.sortTitle2.setFont(font)
        self.sortTitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.sortTitle2.setObjectName("sortTitle2")
        
        self.startSortBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startSortBtn.setEnabled(False)
        self.startSortBtn.setGeometry(QtCore.QRect(600, 40, 100, 25))
        self.startSortBtn.setObjectName("startSortBtn")
        self.startSortBtn.clicked.connect(self.start_simple_sorting)
        
        self.stopSortBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopSortBtn.setEnabled(False)
        self.stopSortBtn.setGeometry(QtCore.QRect(600, 80, 100, 25))
        self.stopSortBtn.setObjectName("stopSortBtn")
        self.stopSortBtn.clicked.connect(self.stop_simple_sorting)
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 160, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        self.multiColumn1CB = QtWidgets.QComboBox(self.centralwidget)
        self.multiColumn1CB.setGeometry(QtCore.QRect(300, 160, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.multiColumn1CB.setFont(font)
        self.multiColumn1CB.setObjectName("multiColumn1CB")
        
        self.sortOrderCB1 = QtWidgets.QComboBox(self.centralwidget)
        self.sortOrderCB1.setGeometry(QtCore.QRect(600, 160, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sortOrderCB1.setFont(font)
        self.sortOrderCB1.setObjectName("sortOrderCB1")
        self.sortOrderCB1.addItems(["Ascending", "Descending"])
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 195, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        self.multiColumn2CB = QtWidgets.QComboBox(self.centralwidget)
        self.multiColumn2CB.setGeometry(QtCore.QRect(300, 195, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.multiColumn2CB.setFont(font)
        self.multiColumn2CB.setObjectName("multiColumn2CB")
        
        self.sortOrderCB2 = QtWidgets.QComboBox(self.centralwidget)
        self.sortOrderCB2.setGeometry(QtCore.QRect(600, 195, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sortOrderCB2.setFont(font)
        self.sortOrderCB2.setObjectName("sortOrderCB2")
        self.sortOrderCB2.addItems(["Ascending", "Descending"])
        
        
        self.startSortBtn2 = QtWidgets.QPushButton(self.centralwidget)
        self.startSortBtn2.setEnabled(False)
        self.startSortBtn2.setGeometry(QtCore.QRect(350, 240, 100, 25))
        self.startSortBtn2.setObjectName("startSortBtn2")
        self.startSortBtn2.clicked.connect(self.multi_column_sort)
        

        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(5, 280, 790, 310))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        
        SortingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SortingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        SortingWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(SortingWindow)
        self.statusbar.setObjectName("statusbar")
        SortingWindow.setStatusBar(self.statusbar)
        
        self.actionOpen_CSV = QtWidgets.QAction(SortingWindow)
        self.actionOpen_CSV.setObjectName("actionOpen_CSV")
        self.actionOpen_CSV.triggered.connect(self.load_csv)
        
        self.actionSave_CSV = QtWidgets.QAction(SortingWindow)
        self.actionSave_CSV.setEnabled(False)
        self.actionSave_CSV.setObjectName("actionSave_CSV")
        self.actionSave_CSV.triggered.connect(self.save_csv)
        
        self.menuOptions.addAction(self.actionOpen_CSV)
        self.menuOptions.addAction(self.actionSave_CSV)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(SortingWindow)
        QtCore.QMetaObject.connectSlotsByName(SortingWindow)
        
        self.sorting_thread = None
        self.stop_flag = False
        self.csv_data = None

    def retranslateUi(self, SortingWindow):
        _translate = QtCore.QCoreApplication.translate
        SortingWindow.setWindowTitle(_translate("SortingWindow", "Sorting Window"))
        self.gobackBtn.setText(_translate("SortingWindow", "<- Back"))
        self.sortTitle.setText(_translate("SortingWindow", "Sorting"))
        self.label.setText(_translate("SortingWindow", "Select Column :"))
        self.label_2.setText(_translate("SortingWindow", "Select Algorithm :"))
        self.label_3.setText(_translate("SortingWindow", "Time Complexity :"))
        self.timeLB.setText(_translate("SortingWindow", "0 ms"))
        self.sortTitle2.setText(_translate("SortingWindow", "Multi-Level Sorting"))
        self.startSortBtn.setText(_translate("SortingWindow", "Start"))
        self.stopSortBtn.setText(_translate("SortingWindow", "Stop"))
        self.label_4.setText(_translate("SortingWindow", "Select Column 1 :"))
        self.label_5.setText(_translate("SortingWindow", "Select Column 2 :"))
        self.startSortBtn2.setText(_translate("SortingWindow", "Start"))
        self.menuOptions.setTitle(_translate("SortingWindow", "Options"))
        self.actionOpen_CSV.setText(_translate("SortingWindow", "Open CSV"))
        self.actionOpen_CSV.setShortcut(_translate("SortingWindow", "Ctrl+O"))
        self.actionSave_CSV.setText(_translate("SortingWindow", "Save CSV"))
        self.actionSave_CSV.setShortcut(_translate("SortingWindow", "Ctrl+S"))
        
    
    def start_simple_sorting(self):
        selected_algorithm = self.algorithmCB.currentText()
        col = self.columnSortCB.currentText()

        # Start sorting in a new thread
        self.sorting_thread = SortingThread(self.csv_data, selected_algorithm, col)
        self.sorting_thread.sorting_finished.connect(self.populate_table)
        self.sorting_thread.time_taken.connect(self.update_time_complexity)
        self.sorting_thread.start()
        self.startSortBtn.setEnabled(False)
        self.stopSortBtn.setEnabled(True)
    
    def stop_simple_sorting(self):
        if self.sorting_thread:
            self.sorting_thread.stop()
            self.stopSortBtn.setEnabled(False)
            self.startSortBtn.setEnabled(True)
            
    def update_time_complexity(self, total_time):
        self.timeLB.setText(f"{total_time} ms")
        self.stopSortBtn.setEnabled(False)
        self.startSortBtn.setEnabled(True)
        
    def multi_column_sort(self):
        selected_col1 = self.multiColumn1CB.currentText()
        selected_col2 = self.multiColumn2CB.currentText()
        order1 = self.sortOrderCB1.currentText() == "Ascending"
        order2 = self.sortOrderCB2.currentText() == "Ascending"

        # Multi-column sort using pandas
        sort_columns = [selected_col1, selected_col2]
        sort_orders = [order1, order2]

        sorted_data = self.csv_data.sort_values(by=sort_columns, ascending=sort_orders)

        self.populate_table(sorted_data)
        
    def load_csv(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open CSV", "", "CSV Files (*.csv);;All Files (*)", options=options)
        
        if file_path:
            try:
                self.csv_data = pd.read_csv(file_path)
                self.populate_table(self.csv_data)
                self.columnSortCB.addItems(self.csv_data.columns)
                self.multiColumn1CB.addItems(self.csv_data.columns)
                self.multiColumn2CB.addItems(self.csv_data.columns)
                self.actionSave_CSV.setEnabled(True)
                self.startSortBtn.setEnabled(True)
                self.startSortBtn2.setEnabled(True)
            except Exception as e:
                QtWidgets.QMessageBox.critical(None, "Error", f"Could not load CSV file: {str(e)}")
                
    def save_csv(self):
        if self.csv_data is not None:
            options = QtWidgets.QFileDialog.Options()
            options |= QtWidgets.QFileDialog.DontUseNativeDialog
            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save CSV", "", "CSV Files (*.csv);;All Files (*)", options=options)
            if file_path:
                self.csv_data.to_csv(f"{file_path}.csv", index=False)
                QtWidgets.QMessageBox.information(None, "CSV Saved", f"Data saved successfully to {file_path}")
        else:
            QtWidgets.QMessageBox.warning(None, "No Data", "No data to save.")

    def populate_table(self, data_frame):
        self.table.setColumnCount(len(data_frame.columns))
        self.table.setRowCount(len(data_frame))
        self.table.setHorizontalHeaderLabels(data_frame.columns)
        
        for i in range(len(data_frame)):
            for j in range(len(data_frame.columns)):
                self.table.setItem(i, j, QtWidgets.QTableWidgetItem(str(data_frame.iloc[i, j])))


class SortingThread(QThread):
    sorting_finished = pyqtSignal(pd.DataFrame) 
    time_taken = pyqtSignal(float)
    
    def __init__(self, data, algorithm, col):
        super().__init__()
        self.data_list = data.to_dict(orient='records')
        self.algorithm = algorithm
        self.col = col
        self.stop_flag = False
    
    def run(self):
        sorted_data = self.data_list
        total_time = 0

        starting_time = time() * 1000
        
        if self.algorithm == 'Bubble Sort':
            sorted_data = bubble_sort(self.data_list, self.col)
        elif self.algorithm == 'Selection Sort':
            sorted_data = selection_sort(self.data_list, self.col)
        elif self.algorithm == 'Insertion Sort':
            sorted_data = insertion_sort(self.data_list, self.col)
        elif self.algorithm == 'Merge Sort':
            sorted_data = merge_sort(self.data_list, self.col)
        elif self.algorithm == 'Quick Sort':
            sorted_data = quick_sort(self.data_list, self.col)
        elif self.algorithm == 'Counting Sort':
            sorted_data = counting_sort(self.data_list, self.col)
        elif self.algorithm == 'Radix Sort':
            sorted_data = radix_sort(self.data_list, self.col)
        elif self.algorithm == 'Bucket Sort':
            sorted_data = bucket_sort(self.data_list, self.col)
        elif self.algorithm == 'Shell Sort':
            sorted_data = shell_sort(self.data_list, self.col)
        elif self.algorithm == 'Gnome Sort':
            sorted_data = gnome_sort(self.data_list, self.col)
        
        ending_time = time() * 1000
        total_time = ending_time - starting_time
        sorted_df = pd.DataFrame(sorted_data)
        
        if not self.stop_flag:
            self.sorting_finished.emit(sorted_df)
            self.time_taken.emit(total_time)
    
    def stop(self):
        self.stop_flag = True


class SortingWindow(QtWidgets.QMainWindow):
    def __init__(self, main_window):
        super().__init__()
        self.ui = Ui_SortingWindow()
        self.ui.setupUi(self)
        self.main_window = main_window
        self.ui.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self._base_size = QtCore.QSize(800, 600)
        self._widget_geometries = capture_widget_geometries(self.ui.centralwidget)

        self.ui.gobackBtn.clicked.connect(self.go_back_to_main)

    def resizeEvent(self, event):
        current_size = self.ui.centralwidget.size()
        if current_size.width() < 100 or current_size.height() < 100:
            super().resizeEvent(event)
            return
        scale_widget_geometries(self._widget_geometries, self._base_size, self.ui.centralwidget.size())
        super().resizeEvent(event)

    def go_back_to_main(self):
        self.main_window.show()
        self.close()
